# V1.9 offline real-image machine-vision replay only.
# This file is NOT a production recipe. Product-specific thresholds remain commissioning parameters.
[PROJECT]
name=AI_Inspection_MachineVisionReplay
version=1.9.0
[PRODUCT]
id=REAL_PCB
[CAMERA:CAM01]
driver=REPLAY
width=640
height=480
[TRIGGER:TRG01]
type=REPLAY
driver=REPLAY
[MODEL:M05]
method=MACHINE_VISION_MEASUREMENT
adapter=MACHINE_VISION_MEASUREMENT
model_path=
model_version=NOT_APPLICABLE
[ROI:R01]
camera_id=CAM01
x=100
y=150
width=360
height=176
[REGION:R01]
name=PCB_Image_Measurement
method=MACHINE_VISION_MEASUREMENT
enabled=true
camera_id=CAM01
trigger_id=TRG01
model_id=M05
roi_id=R01
# Optional thresholds. Fill during commissioning after GOOD/NG sampling.
[RECHECK]
enabled=false
max_attempts=1
min_confidence=0.70
multi_frame=false
[PRODUCT_DECISION]
final_decision=ALL_REQUIRED_REGIONS_PASS
uncertain_policy=NG
missing_region_policy=NG
[PLC:PLC01]
id=PLC01
driver=MOCK
[PLC_REJECT]
enabled=false
output=REJECT
[EVIDENCE]
save_evidence_image=true
save_raw_result=true
save_final_result=true
[AUDIT]
enabled=false
output_path=artifacts/audit
